### ISSUE TITLE
Use Base instead of Core

### ISSUE THREAD

**Issue by stevejb71** [exercism/ocaml#138]
[Base](https://github.com/janestreet/base) is a subset of Core which is more portable (runs on Windows for instance).

Might be good to switch to this once it reaches a stable version.

Environment set up instructions and exercises will need to be updated (I don't anticipate significant code change apart from Makefiles & open directives).

**Comment by superherointj** [comment]
I failed to run it on Windows. 
"opam install core" fails.
Makefile / tests also failed.

**Comment by stevejb71** [comment]
The repo as a whole depends on core, though many of the exercises do not. 

We'll switch to base, which does work on Windows, once it is stable. At the moment I believe it is missing int64 implementations which are needed for one exercise at least.

**Comment by bcc32** [comment]
I think this is broadly a good idea, although just to provide a bit of pushback, there are certain things in Core that are not available in Base, even though they don't depend on Unix (well, the date/time functions do, but I thought I'd list them anyway since they seem important).

```
Data structures and algorithms: Bag, Deque, Doubly_linked, Heap, Rope, Union_find
Date/time: Date, Day_of_week, Ofday, Time
Misc: Memo, String_id, Tuple, Tuple2, Tuple3, Typerep, Univ, Uuid
```

Since there's nothing preventing users from simply importing Core when they need one of the above modules, I suppose the change should go through regardless, but I just thought I'd make a note here.

**Comment by stevejb71** [comment]
Moved the build to jbuilder.
Moved most exercises to using Base.
Meetup uses Core_kernel.
The exercises using Maps/Sets in their interfaces have been left using Core_kernel too - I don't think the new interface to these modules is well documented yet.

Will close.
